# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RpOKz96/J5ydB+FjQFS/maPaRgORfDYMtvNw9/WKqGgujGDXJv0lcVyLVgRzF7rQFeQ82gWvnC6bymslCzq2LoUFSF8+LZQizKi8+ow90jCmkh+UCxjU608VE2UMrHgj0P4ktzaEsbvxzckWt8BNpW7Sa8clsYGLRqViJ/yRPr3Qq6D7UUSuL+4UfJ2/EWDmtE6+KGetuN2jpfukq+ujD11uFtQjE94SMHxOni1lXWDnS4Vc7cosQ7kTkZhiAQaJqknPLu5TvdhzTz2s3awn3h1buNsCdZm7PpzVNiFj1nzzAXVeWh7Lrh8iez7RY0BAAOTwKVb64cUg4282Zl4K3wV53Ljckr7V1AEK+MTBJwlJZg4heV9hAWYB8ZOMpxPvJNZ0NaSoAIEiFvYovBTY/vpYJ3lP9QwAsfu4zU/d0tkPFGtYb4e4OXG5V/jacpRD5YbLD9D9X6MLHr2MYfZstifw1Fjkf1ynPY2ShvSTBUKNiLILqj/9duRQvM8UNjHE9ig5+putc1SlkCv5JZAp+BmUQnQnFr6wxbyOP2KEX9+X3O5OjJUK7Qb7lqZvcSHe1oYoL0mw8WPMIcoCHXnv3pDAw+kbKNqksZ+dd9NDAcXpb7IRB2JW9cmt4UloCL2uJGN+hQg+gf+oqQiD0J0j6PU/RByP9zOEMeNC1xbn9YY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
