# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d2ruCchVdln92XivOEuTJu3Me88uuFlNeDnk7c08ToKI5qX9ZQTiyp8OwhCZ/Yir7Xh54VIxz8VFcphjBHhi8trZXQYhVSW028Jp6cBVHnq1ya2R1cO9VA8ehJdpuR1Y7C5ad9uxjwBPxiynjORfDaYqftukdOu8VAFzOxJahAAigG4970ln7YVYGGIbbUaBZ3/JBNaMlxmeX89y8a9zPFWcr1aNo3TAPmaIpQs8Hyuex0P36m3eUfqVkhQCu7hKpa1B9z7S7kQTme2az22zx+a+0pdoRVs0Kay/Z/KRRpAdW9lIHZG+YlomeDajZbhEd7TMw2qG+O2FevR2Tl25kKVGeP6mcIjbbS8Un05aT170iWJTSV1+wbz9SMe3cvXYFNVSLkAWhbMLA8TXoXOr9DVZ0FFIp5DqZWRgQuethDUKiXoBsnNUokD3PWxC9WqlvH7QaTVGzj8NUD3kSJDB3G1lb3HEtz9nGjxbFRyVopMZtL0CqOo4uAKKQamFvwrGV+o8BLm14xlhqLHZdgYCAjLVjVf+eEGq3Nd6sI1+Nq7c5D2V1gPpwV5rAKEwYoTZQwlBpSYpv2Js7KmSka4Dzl6QVNkdhWqgp++kDoqD1Q1sa/YCLphhqUWI++B5SKglrruTOnjH/j6aH3TuKrmUYKHfGFOFausFzsCeLG9wrpo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
