travis:
  secure:
    BINSTAR_TOKEN: d2ruCchVdln92XivOEuTJu3Me88uuFlNeDnk7c08ToKI5qX9ZQTiyp8OwhCZ/Yir7Xh54VIxz8VFcphjBHhi8trZXQYhVSW028Jp6cBVHnq1ya2R1cO9VA8ehJdpuR1Y7C5ad9uxjwBPxiynjORfDaYqftukdOu8VAFzOxJahAAigG4970ln7YVYGGIbbUaBZ3/JBNaMlxmeX89y8a9zPFWcr1aNo3TAPmaIpQs8Hyuex0P36m3eUfqVkhQCu7hKpa1B9z7S7kQTme2az22zx+a+0pdoRVs0Kay/Z/KRRpAdW9lIHZG+YlomeDajZbhEd7TMw2qG+O2FevR2Tl25kKVGeP6mcIjbbS8Un05aT170iWJTSV1+wbz9SMe3cvXYFNVSLkAWhbMLA8TXoXOr9DVZ0FFIp5DqZWRgQuethDUKiXoBsnNUokD3PWxC9WqlvH7QaTVGzj8NUD3kSJDB3G1lb3HEtz9nGjxbFRyVopMZtL0CqOo4uAKKQamFvwrGV+o8BLm14xlhqLHZdgYCAjLVjVf+eEGq3Nd6sI1+Nq7c5D2V1gPpwV5rAKEwYoTZQwlBpSYpv2Js7KmSka4Dzl6QVNkdhWqgp++kDoqD1Q1sa/YCLphhqUWI++B5SKglrruTOnjH/j6aH3TuKrmUYKHfGFOFausFzsCeLG9wrpo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
