travis:
  secure:
    BINSTAR_TOKEN: RpOKz96/J5ydB+FjQFS/maPaRgORfDYMtvNw9/WKqGgujGDXJv0lcVyLVgRzF7rQFeQ82gWvnC6bymslCzq2LoUFSF8+LZQizKi8+ow90jCmkh+UCxjU608VE2UMrHgj0P4ktzaEsbvxzckWt8BNpW7Sa8clsYGLRqViJ/yRPr3Qq6D7UUSuL+4UfJ2/EWDmtE6+KGetuN2jpfukq+ujD11uFtQjE94SMHxOni1lXWDnS4Vc7cosQ7kTkZhiAQaJqknPLu5TvdhzTz2s3awn3h1buNsCdZm7PpzVNiFj1nzzAXVeWh7Lrh8iez7RY0BAAOTwKVb64cUg4282Zl4K3wV53Ljckr7V1AEK+MTBJwlJZg4heV9hAWYB8ZOMpxPvJNZ0NaSoAIEiFvYovBTY/vpYJ3lP9QwAsfu4zU/d0tkPFGtYb4e4OXG5V/jacpRD5YbLD9D9X6MLHr2MYfZstifw1Fjkf1ynPY2ShvSTBUKNiLILqj/9duRQvM8UNjHE9ig5+putc1SlkCv5JZAp+BmUQnQnFr6wxbyOP2KEX9+X3O5OjJUK7Qb7lqZvcSHe1oYoL0mw8WPMIcoCHXnv3pDAw+kbKNqksZ+dd9NDAcXpb7IRB2JW9cmt4UloCL2uJGN+hQg+gf+oqQiD0J0j6PU/RByP9zOEMeNC1xbn9YY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
