travis:
  secure:
    BINSTAR_TOKEN: K++y5vHl89UqfmjfXRXcsNcibvjHd17gRsqfbcjQJdiGAfSiJZl/xjmXD0Wn0SYAinuYuGCmBmrnflUuiScIIq3pkqoli/arv+xRXgCxW/iJgVzyqFOwCyBDGD26zu55Y9wGeuhuBYcZFuyfgrz6Z6RL/RA4nGD6bBFR6mzNnWpxsk9E0F+X1ZXcxb4x7Bq+NYU+GU8FC5pQK/G4iZTHaeTtsvtXMUFC/ci883sPHLOxHV3wHPwgHlKgcqUnEpy9Y7Nvb6B0pWl/qa9helGuk4mnX6mlbdUUT9ciwH7WVzdMWbwsEmIE9qfCem+dgB9nSN3ZOzAbs7MrA97lU/n1TzSSubEZg2SI7klCX3uBEm9GLPTWnFi9q7E0aeS80R8ZJ2sOqVxFE4eP0PssI4t2zghd3DYQfCROB7dQCGGizbrojIqyperx50p6aoiqhEn7WlMOuFvnbD4UT/ZJGB0OhcEx3TEAWvCZcIJ02knhJWNmS/UzQv2tpGBPimXHZJrFYA4AGa4bZdQYIvkzAu0pvqGTbYkHvV3rM19XHZM3Vzxhm+xpUEttBzfgioSP2Kr7qFjqk81jo4WZK94zE9RkmhA4MU1HSAVgNdTgdMc+0NXWd3DzpCj8Iw+M0Y7Iji6mhxa4ed3y/VRnG6YvlR0tKhCpeOFSeYR9SjedwAUePUY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
