travis:
  secure:
    BINSTAR_TOKEN: BSPu6cVRHlGhrTalmEKNPC7O0Qp1YXgZrZNyuOFjSXvPrMkKtpHxiInT+wxHIqKxm9sBECFWlDASfHL81rICx3pdMAQIlOCW1ZvGLE89OVnLbq0cEZu/NYv6K3GyUNpDvgr58gdC0E52eony9xvcMNxrO5U50B9hRBEfEzMkpUuecI9ARdcdlCTrLzCLwS0Fc32vbn/jKkosf+sONcYW5caB67aR6dv6+6N3zzIwR3ezoiev3Bwurw8Ea8FJY0Ewytvm8cVgwaAfPUIz6NZ0SBtznh9jSXqtqR3gcc+wITdva2laLY8BzBHjJPWdn8mrp1UtpYqSOh2nxaorl91mEbSFSuNgWi5kqvbkAmJJwhPv5pW6xClpCjUFykcBAJg2aOYtrd+VX/ifgD34d9B3A17vPlysUx/dFlKRY83ashuoLn7/iq4yFbPmDOL7gshIj5Hwb93yPGMKBxJ2Qj7zmscGvFmeCWDAyovbRtVH+74fQWGtTNAiYUApRailHstXOaeuNlAtC3zjHNQ/PnpnCDCbhiMJnJGyx02Yz8vcRg10HCzJbXaF66+60vqtO0BItzYb9EG5SRLqDUSKLgJS+Lp0moaFh40p/uIG/4p4bx8KrF/2OkEHNJQOwPfrpp6/MXSN3HgLHoZZnjSpj3bC6E2aYvDR4dlXe5+jaM+DKtU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
