travis:
  secure:
    BINSTAR_TOKEN: XdkFCFZOHxamnLljdrQsaW6KCvfcPX87zAfnFee3ku+SnqXt+33o9QDWssDHYRmjjxKOI3D/9kxI9/13lmFlFMhfxPkIczzEhJ2r3ID7aVg7c67p+C7fnVerNA4mVZ15o41N9Ovn0rUENaH50/b7yECle6QVkjNoFW+Xb8bWPXwXPACBpNPWVKGYpHCV3Thbw25Ow801reD3Fbbx5K5J7+xGjdMOn2Yg0JfmIm/SUJnXaKd7N700/+qVkXlpith69rlfUvOF6G/epp2DUqkeujpMbPl8DYXFp5jCK0JPNcrdYqKeKsif+34YcrXemHT/wg22YYoS767tLEqX6Djv5eYyjs+qIFxveVANJJQMJCgPtCJOOMvr+QeCpithRu7oTwquU+TMB5YxP5zCDhKUaVVfJLua3GsOOZOJ0WjTnyxbq5GtBjyoDT4H9wY1bnmPzeq7ukLreQlH32cg8rUWpjqi6HyN4nnLfmFnak1sTUTGEFNIEPooyvQBqtHoTtqFX9fJazDco7E8OgZXPMHLPFvoKBy4KwVWhdK1wItVoaErjfjrFAeOj3VHS0qYdbigtOTG+SnpJFosTeuOxnCX6kGEFPobUzmztPRNxtp6VlF/Y2qHe6Uiw9HED/aoCcPWubclsvUFibRSOaOLnCXDKWFy/JYAmTrQ6a9XQP2h08I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
